version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "word_count:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper

  pyspark:
    image: integration-test-pyspark
    expose:
      - "9000"
    command: bash
    volumes:
      - .:/app/
      - ./dependencies:/app_dependencies
      - ./tmp:/test_output
    links:
      - kafka
      - elasticsearch

  slave:
    image: integration-test-fluentd
    volumes:
      - ./:/app
      - ./data:/data
      - ./tmp:/test_output
    links:
      - kafka

  elasticsearch:
    image: integration-test-elasticsearch
    environment:
      - Des.network.host=0.0.0.0
    expose:
      - "9200"
